### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by itsjustnickdev** [KMoszczyc/yt-dlp-back#1]
It just doesnt work lol keep getting a error Not Found

**Comment by KMoszczyc** [comment]
Hey, could you be a little more specific? xd

**Comment by itsjustnickdev** [comment]
(ipadress) - - [20/Nov/2022 15:31:36] "GET /getInfo/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1UHmQANFtNs HTTP/1.1" 404 -

**Comment by KMoszczyc** [comment]
Still not really specific, url and session dir should be send as a json, not as parameters.
Like that in Postman.
![image](https://user-images.githubusercontent.com/61971053/202923694-aa666118-8731-48bf-8c36-1f76b674d189.png)

**Comment by itsjustnickdev** [comment]
I used https://github.com/KMoszczyc/youtube-converter your sites code so I think it's something with backend bcs it can't find anything on it

**Comment by KMoszczyc** [comment]
I've added local branch for local deployment, try it out: https://github.com/KMoszczyc/youtube-converter/tree/local

**Comment by itsjustnickdev** [comment]
script.js:154 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'src')
    at clearData (script.js:154:23)
    at HTMLFormElement.getSongInfo (script.js:81:5)

**Comment by KMoszczyc** [comment]
Dude, you gotta be more descriptive with the issue. Like did you try to deploy locally or in the cloud. After what action did it happen, in what moment?

**Comment by nickdevnl** [comment]
Cloud ofcourse

**Comment by itsjustnickdev** [comment]
Cloud ofcourse

**Comment by KMoszczyc** [comment]
Did it work locally?

**Comment by itsjustnickdev** [comment]
Can only test it on my servers in datacenter rn my pc is like 20 years old and crash when installing nodejs or py😂

**Comment by itsjustnickdev** [comment]
Can give you access to both servers on my hosting so you can check it out

**Comment by KMoszczyc** [comment]
Man, I don't really have time for it. Just go for the local branch and try to debug it yourself as it's working for me.
